---
title: "Exploring Gapminder Dataset"
author: "Abdullah Farouk"
date: '2017-09-22'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I begin my analysis by installing the gapminder and tidyverse packages. This is followed by

```{r}
library(gapminder)
library(tidyverse)
```

##Smell testing data##


I can learn more about my variables using the following function call
```{r}
sapply(gapminder, class)
glimpse(gapminder)

```
The sappy function allows me to get the results back in a vector form.


Create temp variable to get data on Asian subcontinent
```{r}
copy_1 <- gapminder

# I want to analyze Sri Lanka's data
temp <- copy_1 %>% 
  filter(continent == 'Asia')

```



```{r}
#First I back out GDP

temp <- mutate(temp, log_gdp = log(gdpPercap*pop))
SL <- filter(temp, country == 'Sri Lanka')

#I want to visualize time trends within Sri Lanka

sl_lyfexp_trend <- ggplot(SL, aes(year, lifeExp))

#How does each variable evolve over time?

sl_lyfexp_trend + geom_bar( stat = "identity", aes(fill = year))

#People are living for longer. Has this had an effect on GDPor on population for that matter?

```

```{r}
#I use a log scale to normalize for the differences in the magnitude of the numbers
sl_gdp_vs_pop <- ggplot(SL, aes(year)) + geom_line(aes(y = log(gdp), colour = 'gdp')) + geom_line(aes(y = log(pop), colour = 'pop')) + ylab('Values of gdp and Population')

sl_gdp_vs_pop

#We notice that GDP and population have both been growing. However gdp has been growing at a much faster rate.

#Is this something that is common trend among all Asian countries? To explore this idea I create a scatter plot of gdp of different countries across time. I vary the sizes of the dots by the population in each country to identify whether an inverse relationship exists

temp %>% 
  ggplot(aes(x= year, y = log(gdp))) + geom_point(aes(colour = country, size = pop))

#We notice that there are 3 Asian countries that have experienced tremendous GDP growth. They are China, Israel and India. What is interesting is that China and India have been able to do so despite having a very large population (size of a country's population can be inferred from the size of a point in the graphic). 

# Is there a possible link between life expectancy and gdp growth. Is it perhaps a country's ability to ensure it's population lives for longer that enables it to prosper economically?

```

```{r}
#To answer this I subdivide my data further

top_3_asian_econ <- filter(temp, country %in% c("China", "India", 'Israel', 'Sri Lanka'))

asia_life_exp_bar_plot <- top_3_asian_econ %>% 
  ggplot(aes(x = country, y = lifeExp)) + geom_boxplot(fill = 'green', colour = 'black') + theme_bw() + ggtitle("Life Expectancy of Top 3 Asian Economies vs Sri Lanka")

asia_life_exp_bar_plot

# The distributions paints an interesting picture. Notice how the distribution of life expectancy in India and China are much wider than that of Sri lanka and Israel. Further they have a lower median value of life expectancy than Sri Lanka's and Israel's. 

#Perhaps their economic boom stems from the fact that their populations are young. 

```

```{r}
#How does Sri Lanka compare to the top 3 in terms of gdp and population growth?  

rank <- top_3_asian_econ %>% 
  group_by(country) %>% 
  summarise_each(funs(mean), pop, lifeExp, log_gdp, gdpPercap)
       
rank

# Since China has the largest average population and log gdp values. I normalize everyone else's values of population and log gdp using China's. The folllowing code is cited from stat 545 lecture on dplyr (http://stat545.com/block010_dplyr-end-single-table.html)

```

```{r}
#First extract data on China
china <- top_3_asian_econ %>%
  filter(country == "China")

top_3_asian_econ <- mutate(top_3_asian_econ, tmp = rep(china$gdp, n_distinct(country)), log_gdp_rel = gdp / tmp, tmp = NULL, tmp_1 = rep(china$pop,n_distinct(country)), pop_rel = pop/tmp_1, tmp_1 = NULL)
         
#Now i plot the trends in population and gdp growth. The code was sourced from stackexchange. (https://stackoverflow.com/questions/29357612/plot-labels-at-ends-of-lines)

```

```{r}
rel_gdp_performance <- ggplot(top_3_asian_econ) + 
  geom_line(aes(x = year, y = log_gdp_rel, group = country, colour = country))

rel_pop_performance <- ggplot(top_3_asian_econ) + 
  geom_line(aes(x = year, y = pop_rel, group = country, colour = country))

rel_pop_performance
rel_gdp_performance

```

